# library(shiny)
library(leaflet)
library(raster)
library(shinythemes)
library(shinyWidgets)
library(shinycssloaders)
library(sf)
library(leafem)
library(rgdal)

acuaculture <- readOGR(dsn = "data/acuiculture_WGS84.shp", )
cables <- readOGR(dsn = "data/cables_disolve_WGS84.shp")
energy_device <- readOGR(dsn = "data/energy_devi_WGS84.shp")
militar_area <- readOGR(dsn = "data/militar_area_linea_WGS84.shp")
mpa <- readOGR(dsn = "data/MPA_linea_WGS84.shp")
pipeline <- readOGR(dsn = "data/pipeline_WGS84.shp")
study_area <- readOGR(dsn ="data/study_area_paises_WGS84.shp")
